decoration_items = {
    "Carved Pumpkin": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Decorative Anchor": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Decorative Glass Buoy Blue": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Decorative Glass Buoy Red": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Decorative Hanging Buoy": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Decorative Life Preserver": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Decorative Ship Wheel": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Galaxy Vase": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Large Cotton Bunting Red": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Large Cotton Bunting Regal": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Large Nylon Bunting Green": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Large Nylon Bunting Purple": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Orange Vase": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Plant Vase": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Purple Vase": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Red Vase": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Round Pot": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Small Cotton Bunting Red": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 0.5},
    "Small Cotton Bunting Regal": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 0.5},
    "Small Nylon Bunting Green": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 0.5},
    "Small Nylon Bunting Purple": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 0.5},
    "Square Pot": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Swirl Vase": {"Type": "Decoration", "Room": "Decoration", "Dim. Return %": "40%", "Value": 1},
    "Rug Large": {"Type": "Decoration", "Room": "Rug", "Dim. Return %": "50%", "Value": 2},
    "Rug Medium": {"Type": "Decoration", "Room": "Rug", "Dim. Return %": "50%", "Value": 1},
    "Rug Small": {"Type": "Decoration", "Room": "Rug", "Dim. Return %": "50%", "Value": 0.5},
    "Limestone Bison Statue": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "30%", "Value": 1},
    "Limestone Otter Statue": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "60%", "Value": 0.2},
    "Limestone Owl Statue": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "60%", "Value": 0.2},
    "Limestone Wolf Statue": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "50%", "Value": 0.5},
    "Stuffed Alligator": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "10%", "Value": 3},
    "Stuffed Bison": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "10%", "Value": 3},
    "Stuffed Elk": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "10%", "Value": 3},
    "Stuffed Goat": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "10%", "Value": 3},
    "Stuffed Jaguar": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "10%", "Value": 3},
    "Stuffed Wolf": {"Type": "Decoration", "Room": "Statue", "Dim. Return %": "20%", "Value": 2.5}
}
