lighting_items = {
    "Brazier": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 1.2},
    "Candle Stand": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 1.4},
    "Ceiling Candle": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 1.4},
    "Electric Wall Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 2.5},
    "Large Festive Paper Lantern": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 2},
    "Large Paper Lantern": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 2},
    "Modern Double Street Light": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Modern Street Light": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Small Paper Lantern": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 2},
    "Steel Abstract Fixture": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Steel Ceiling Light": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Steel Floor Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Steel Hanging Fixture": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Steel Hanging Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Steel Kitchen Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 0.8},
    "Steel Searchlight": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "50%", "Value": 3},
    "Steel Square Fixture": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Steel Table Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Stone Brazier": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 1},
    "Streetlamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 3},
    "Tallow Candle": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 0.8},
    "Tallow Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 1.2},
    "Tallow Wall Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 1.2},
    "Torch Stand": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 0.8},
    "Wall Candle": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 1.2},
    "Wooden Ceiling Light": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 2},
    "Wooden Floor Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 2},
    "Wooden Kitchen Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "50%", "Value": 1},
    "Wooden Table Lamp": {"Type": "Lighting", "Room": "Lights", "Dim. Return %": "70%", "Value": 2}
}
