seating_items = {
    "Adorned Ashlar Basalt Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 3},
    "Adorned Ashlar Basalt Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 2},
    "Adorned Ashlar Stone Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 3},
    "Adorned Ashlar Stone Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 2},
    "Ashlar Basalt Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 2.5},
    "Ashlar Basalt Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 1.7},
    "Ashlar Stone Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 2.5},
    "Ashlar Stone Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 1.7},
    "Composite Birch Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 2.5},
    "Composite Birch Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 1.7},
    "Composite Hardwood Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 2.5},
    "Composite Hardwood Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 1.7},
    "Composite Lumber Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 2.5},
    "Composite Lumber Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 1.7},
    "Hewn Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 1},
    "Hewn Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 0.5},
    "Hewn Softwood Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 1},
    "Hewn Softwood Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 0.5},
    "Lumber Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 1.5},
    "Lumber Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 1},
    "Mortared Granite Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 1},
    "Mortared Granite Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 0.5},
    "Mortared Stone Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 1},
    "Mortared Stone Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 0.5},
    "Softwood Lumber Bench": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "50%", "Value": 1.5},
    "Softwood Lumber Chair": {"Type": "Seating", "Room": "Chair", "Dim. Return %": "70%", "Value": 1},
    "Adorned Ashlar Basalt Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 3.5},
    "Adorned Ashlar Stone Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 3.5},
    "Ashlar Basalt Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 3},
    "Ashlar Stone Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 3},
    "Composite Birch Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 3},
    "Composite Hardwood Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 3},
    "Composite Lumber Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 3},
    "Hewn Softwood Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 1},
    "Hewn Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 1},
    "Lumber Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 2},
    "Mortared Granite Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 1},
    "Mortared Stone Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 1},
    "Softwood Lumber Table": {"Type": "Seating", "Room": "Table", "Dim. Return %": "60%", "Value": 2}
}
